Connect About page to oacore/content repository
oacore/about pull request #379
Opened 2021-04-09 16:15 UTC by vv2529

2021-04-12 09:59 UTC, viktor-yakubiv requested changes
I am sorry, I cannot look into your PR deeply now but I will certainly do it a bit later. Please, have a look at my brief remarks.

Would you mind if I take over this PR and add or edit some things when you are done?

Great start! 👍 And thanks for understanding

2021-04-12 09:59 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +        ...data.about.research,
Try creating a file structure in a way, that lets you avoid `.about.` part

2021-04-12 09:59 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +          <Markdown>{data.about.mission.content}</Markdown>
Does NetlifyCMS render this  as markdown body or as a _content_ field in the front-matter?

2021-04-12 09:59 UTC, viktor-yakubiv commented on netlify-cms.config.yml
> +      - name: video
Please, merge this into a `mission` for now as a nested object-widget.

2021-04-12 09:59 UTC, viktor-yakubiv commented on netlify-cms.config.yml
> +          widget: string
Almost all these fields apart from the most obvious ones should contain a hint that expresses how the content is used and why it's needed.

It's a pert of the user experience of the internal system for your team members. Better explanation here – fewer questions in the future.

2021-04-12 10:20 UTC, vv2529 commented on pages/about/index.jsx
> +        ...data.about.research,
Should `about` be omitted? This way its child objects will be placed directly in `data` and merged with other objects, such as the already existing `data.team`. I believe it won't lead to errors though.

2021-04-12 10:23 UTC, vv2529 commented on pages/about/index.jsx
> +          <Markdown>{data.about.mission.content}</Markdown>
As a _content_ field. I can fix that, but, generally speaking, what if a file contains more than one markdown fields? The body can only fit one.

2021-04-12 11:40 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +        ...data.about.research,
Exactly, this how data object was designed. `team.members` should be places in there.

2021-04-12 11:42 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +          <Markdown>{data.about.mission.content}</Markdown>
That is why it's a set of Markdown files instead of one large YAML file.

Specifically, _mission_ has a title, short title, and body. Most of other sections are the same.

2021-04-12 11:44 UTC, viktor-yakubiv commented
I forgot to say, don't worry about the synchronisation of content files in oacore/content#13. It can be done once in the end of this PR.

2021-04-12 13:56 UTC, viktor-yakubiv commented on netlify-cms.config.yml
> +          widget: string
@vv2529 you took this too far. I meant adding `hint` property where it's needed expressing how the data is used.

2021-04-12 13:56 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +  content = content.map((section) => {
Use `.forEach` without assignment to fix this issue.

2021-04-12 13:56 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +          label: data.research.action,
It would be good to review these call-to-action captions providing more self-explained property names. I might do it myself.

2021-04-12 13:56 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +    contentObject[section.id] = section
We should this part into `content/index.js`

2021-04-15 14:43 UTC, vv2529 commented
Apologies for the messy commit history, I'll try to do a better job combining branches next time

2021-04-15 14:49 UTC, vv2529 commented on pages/about/index.jsx
> +  content = content.map((section) => {
Should the CMS config be changed again? I'm not sure what to do, the hints look quite okay to me

2021-04-15 14:59 UTC, viktor-yakubiv commented on pages/about/index.jsx
> +  content = content.map((section) => {
I will pick it if you don't mind. You did a great job, thank you! 🙂

2021-04-19 13:36 UTC, viktor-yakubiv commented
@vv2529 would you like to review it one more time or I can merge this?

If you do, here is the preview link: [CMS](https://about-git-netlify-cms-oacore.vercel.app/edit.html) and [page](https://about-git-netlify-cms-oacore.vercel.app/about). Due to the complexity of the auth provider, we cannot host CMS on every preview domain.

2021-04-19 13:51 UTC, viktor-yakubiv approved these changes

2021-04-19 13:51 UTC, viktor-yakubiv commented
I couldn't deploy it properly, we will need to merge it dangerously but maybe tomorrow due do ElasticSearch instability.

2021-04-23 13:13 UTC, merged

2021-04-23 13:15 UTC, viktor-yakubiv commented
@vv2529 congratulations on your first PR merged 🎉 It was not merged first, but it is the first one you created 😉

2021-04-23 13:39 UTC, vv2529 commented
Great!